"""Six documents, in the shape a reader returns them, and one warning.

READ THIS BEFORE QUOTING ANY NUMBER THAT CAME OUT OF THIS FILE
================================================================

    THESE FIXTURES PROVE PARSER AND VALIDATION BEHAVIOUR.
    THEY PROVE NOTHING WHATSOEVER ABOUT PRODUCTION OCR ACCURACY.

Every character below was TYPED BY HAND into the shape a reading engine
produces. Not one of them was read off a photograph, and no photograph of any
of them exists. They answer questions of the form "given exactly these
characters, does the parser find the IGST figure and refuse the CGST/SGST
contradiction". They cannot answer "does tesseract produce these characters
from a real bill", because nobody has ever handed this repository a real
Indian GST invoice to try.

A SYNTHETIC RENDER IS NOT A PHOTOGRAPH, and this repository has already paid
for forgetting that once. `artifacts/ground_truth` scored 20/20 on a tier that
was inventing every total, because the corpus was generated by the same code
being measured - a corpus measuring its own generator.
`docs/EXTRACTION_MEASURED.md` carries the correction. This file carries the
warning so it travels with the data rather than living in a document nobody
opens.

WHY TEXT AND WORD LISTS RATHER THAN IMAGES
--------------------------------------------
Pillow can draw text onto a canvas and tesseract can read it back, and the
result would look like a measurement. It would be a measurement of Pillow's
font rendering. The honest version of "captured reading output" is the text and
the per-word scores, which is what a real capture would give us - so that is
what these are, and the day real redacted captures arrive they drop into
exactly this shape. `docs/INVOICE_EXTRACTION_FRAMEWORK.md` holds the contract.

NO REAL PARTY, NO REAL REGISTRATION NUMBER
--------------------------------------------
Every name is invented. Every GSTIN below is shaped like a GSTIN - it has to
be, or it would test nothing - and none belongs to a real registered person:
the PAN blocks spell things no registrar issues.

WHAT EACH ONE IS FOR
---------------------
    INTRA_STATE       a complete CGST/SGST bill that adds up. The happy path.
    INTER_STATE       IGST, a place of supply, several lines.
    WITH_DISCOUNT     a discount, a round-off, an amount in words, an IRN and
                      an e-way bill.
    NOT_AN_INVOICE    a museum catalogue page. Reads perfectly; is not a bill.
    BARELY_READABLE   what a bad photograph comes back as.
    MISSING_FIELDS    a real bill with no number and no date on it.
"""

from __future__ import annotations

from dataclasses import dataclass

from accountant.invoice.parse import Reading, Word

#: What the text-layer tier is entitled to state about its own certainty.
#: `cage/confidence.EXACT` is 1.0 and means "there is no pixel and no estimate";
#: these fixtures are characters, so that is the honest score for them.
TEXT_LAYER: str = "pdf_text_layer"

#: The name a reading rebuilt from word scores carries in these fixtures.
PHOTOGRAPH: str = "free_ocr"


@dataclass(frozen=True)
class Fixture:
    """One hand-written document and what a person reading it would say.

    `expected` is deliberately sparse. It holds the facts a test asserts
    EXACTLY - a paise figure, a GSTIN, a status - and not a full transcription,
    because an expectation nobody checked by hand is not a ground truth, it is
    the parser's own output written down twice.
    """

    name: str
    text: str
    expected: dict[str, object]


# =============================================================================
# 1. intra-state: CGST and SGST, several lines, and it adds up
# =============================================================================
#
# The arithmetic, so a reader can check it without running anything:
#
#   line 1   2 x 1,500.00           = 3,000.00
#   line 2   3 x   800.00           = 2,400.00
#   line 3   1 x 1,600.00           = 1,600.00
#                            taxable  7,000.00
#   CGST 9%                            630.00
#   SGST 9%                            630.00
#                              total  8,260.00

INTRA_STATE = Fixture(
    name="intra_state_cgst_sgst",
    text="""\
TAX INVOICE

Supplier: NORTHFIELD STATIONERY PRIVATE LIMITED
GSTIN: 27AAQCS9214X1ZK
Address: 14 Turner Road, Bandra West, Mumbai 400050

Bill To: KHANNA ADVISORY SERVICES LLP
GSTIN: 27AACFK7391M1Z9

Invoice No: NSP/2026/0417
Invoice Date: 2026-07-14
Purchase Order No: PO-88231
Place of Supply: Maharashtra

Description        HSN     Qty   Rate      Taxable
Copier paper A4    4802    2     1500.00   3000.00
Ring binders       4820    3     800.00    2400.00
Marker pens        9608    1     1600.00   1600.00

Taxable Value: 7000.00
CGST 9%: 630.00
SGST 9%: 630.00
Total: 8260.00
""",
    expected={
        "supplier_gstin": "27AAQCS9214X1ZK",
        "buyer_gstin": "27AACFK7391M1Z9",
        "supplier_state_code": "27",
        "invoice_number": "NSP/2026/0417",
        "invoice_date": "2026-07-14",
        "place_of_supply": "Maharashtra",
        "line_count": 3,
        "line_taxable_paise": (300000, 240000, 160000),
        "hsn": ("4802", "4820", "9608"),
        "taxable_paise": 700000,
        "cgst_paise": 63000,
        "sgst_paise": 63000,
        "total_tax_paise": 126000,
        "grand_total_paise": 826000,
    },
)


# =============================================================================
# 2. inter-state: one integrated tax, a place of supply in another state
# =============================================================================
#
#   line 1   10 x 450.00   = 4,500.00
#   line 2    4 x 275.00   = 1,100.00
#                  taxable   5,600.00
#   IGST 18%                 1,008.00
#                    total   6,608.00

INTER_STATE = Fixture(
    name="inter_state_igst",
    text="""\
TAX INVOICE

Supplier: DECCAN COMPONENTS AND TOOLS PRIVATE LIMITED
GSTIN: 29AAECD4471P1ZQ
Address: Plot 42 Peenya Industrial Area, Bengaluru 560058

Bill To: RANJIT ENGINEERING WORKS
GSTIN: 27AAGFR2210K1ZB

Invoice No: DCT-2026-1188
Invoice Date: 21 JUN 2026
Place of Supply: Maharashtra

Description        HSN     Qty   Rate     Taxable
Bearing housing    8483    10    450.00   4500.00
Drive coupling     8483    4     275.00   1100.00

Taxable Value: 5600.00
IGST 18%: 1008.00
Total: 6608.00
""",
    expected={
        "supplier_gstin": "29AAECD4471P1ZQ",
        "buyer_gstin": "27AAGFR2210K1ZB",
        "supplier_state_code": "29",
        "invoice_number": "DCT-2026-1188",
        "invoice_date": "2026-06-21",
        "place_of_supply": "Maharashtra",
        "line_count": 2,
        "line_taxable_paise": (450000, 110000),
        "taxable_paise": 560000,
        "igst_paise": 100800,
        "cgst_paise": None,
        "total_tax_paise": 100800,
        "grand_total_paise": 660800,
    },
)


# =============================================================================
# 3. a discount, a round-off, words, and the two e-invoicing identifiers
# =============================================================================
#
#   line 1   5 x 1,200.00 less 500.00 = 5,500.00
#   line 2   2 x   740.00 less   0.00 = 1,480.00
#                                       6,980.00 taxable
#   CGST 6%                               418.80
#   SGST 6%                               418.80
#                                        7,817.60
#   Round Off                               -0.60
#                                 total  7,817.00
#
# The IRN is sixty-four hexadecimal characters, which is the shape the invoice
# registration portal returns. The e-way bill number is twelve digits. Both are
# invented and both are SHAPE-checked only - see `parse.valid_gstin` for why an
# unverified checksum is worse than none.

WITH_DISCOUNT = Fixture(
    name="discount_round_off_and_words",
    text="""\
TAX INVOICE

Supplier: SARAVANA TEXTILE MILLS PRIVATE LIMITED
GSTIN: 33AABCS1429J1Z7

Bill To: VELAN GARMENTS
GSTIN: 33AAHFV8802L1ZM

Invoice No: STM-4471
Invoice Date: 19/08/2026
IRN: 4a7f19c0b3e25d8146af90cc7b2e5310df6a48b9c012e37f5a9d4b6e8c1f2037
E-Way Bill No: 481920375566
Place of Supply: Tamil Nadu

Description        HSN     Qty   Rate      Discount   Taxable
Cotton shirting    5208    5     1200.00   500.00     5500.00
Poplin roll        5208    2     740.00    0.00       1480.00

Taxable Value: 6980.00
CGST 6%: 418.80
SGST 6%: 418.80
Round Off: -0.60
Total: 7817.00
Amount in Words: Rupees Seven Thousand Eight Hundred And Seventeen Only
""",
    expected={
        "supplier_gstin": "33AABCS1429J1Z7",
        "invoice_number": "STM-4471",
        # `19/08/2026` and not `09/08/2026`, and the difference is the point.
        # Nineteen cannot be a month, so arithmetic settles the order and no
        # convention was assumed. `09/08/2026` could be the 9th of August or the
        # 8th of September, and `parse.date_from` refuses it - which
        # `test_invoice_parse.py` asserts separately rather than hiding here.
        "invoice_date": "2026-08-19",
        "irn": ("4a7f19c0b3e25d8146af90cc7b2e5310df6a48b9c012e37f5a9d4b6e8c1f2037"),
        "eway_bill": "481920375566",
        "line_count": 2,
        "line_discount_paise": (50000, 0),
        "line_taxable_paise": (550000, 148000),
        "taxable_paise": 698000,
        "cgst_paise": 41880,
        "sgst_paise": 41880,
        "round_off_paise": -60,
        "grand_total_paise": 781700,
        "amount_in_words": ("Rupees Seven Thousand Eight Hundred And Seventeen Only"),
    },
)


# =============================================================================
# 4. not an invoice at all
# =============================================================================
#
# Deliberately a document that READS PERFECTLY. The point of this fixture is
# that a clean reading and a bill are different things - the failure this whole
# package exists to separate. Nothing a bill prints is on it: no invoice, no
# tax, no amount, no registration number, no rupee figure.
#
# THE WORDING HAD TO BE CHOSEN CAREFULLY, AND THAT IS A FINDING RATHER THAN AN
# INCONVENIENCE. The first draft of this fixture read "Book of hours" and
# "wooden boards", and `invoicelike.looks_like_a_bill` reported that it PRINTS A
# CURRENCY - because that signal's pattern is `₹|Rs\\.?|INR` with no word
# boundary, so the `rs` inside `hours` matches. One signal is not two, so the
# verdict was still "not a bill", but the SIGNAL LIST shown to a person named a
# currency that is not on the page.
#
# `invoicelike.py` is not this package's to edit. The finding is recorded here
# and in `docs/INVOICE_EXTRACTION_FRAMEWORK.md`, and this fixture is worded to
# fire NOTHING, so it tests `UNKNOWN_DOCUMENT` rather than a false signal.

NOT_AN_INVOICE = Fixture(
    name="museum_catalogue_page",
    text="""\
CATALOGUE OF THE WESTERN MANUSCRIPT COLLECTION

Plate XIV. A book of the office, use of Sarum, in Latin.
Southern Netherlands, probably Bruges, circa 1470.
Vellum, 178 leaves, 14 lines to a page, ruled in pale red.
Binding contemporary, blind-stamped calf over wooden panels,
rebacked in the nineteenth century with the spine laid down.
The calendar is written in alternating red and blue, with the
feasts of the diocese entered in a slightly later hand.
""",
    expected={"signals": (), "status": "unknown_document"},
)


#: A document that fires ONE signal and stops there - readable, and confidently
#: not a bill. Kept beside the catalogue rather than replacing it, because
#: `NON_INVOICE` and `UNKNOWN_DOCUMENT` are different statuses and a fixture set
#: that only reached one of them would leave the other untested.
#:
#: `Delivery Challan` fires "names itself a bill" and nothing else: there is no
#: tax word, no amount word, no registration number and no rupee figure on it.
A_DELIVERY_NOTE = Fixture(
    name="delivery_challan_no_figures",
    text="""\
DELIVERY CHALLAN

Consignment released from the Bhiwandi warehouse on the morning run.
Four cartons, sealed, checked against the picking slip by the
supervisor on duty and signed for at the gate.

Vehicle KA 05 MJ 7712. Driver carries the gate pass.
Nothing in this consignment is fragile.
""",
    expected={"signals": ("names itself a bill",), "status": "non_invoice"},
)


# =============================================================================
# 5. a bad photograph
# =============================================================================
#
# What a reading engine returns from something out of focus and badly lit: a
# handful of characters, most of them not letters. This is the shape that used
# to be indistinguishable from a total reading failure, and separating the two
# is the reason `status.py` exists.

BARELY_READABLE = Fixture(
    name="bad_photograph",
    text="|| :- ~~ ,,, \\\\ // ~~ ;; '' .. -- || ~~ ,, ..\n=== ... ;;; ~~~ ||| ,,,\n",
    expected={"legible_share_below": 0.5},
)


# =============================================================================
# 6. a real bill with mandatory fields missing
# =============================================================================
#
# It looks like a bill and it reads well. It has a supplier, a registration
# number, line items and a total that adds up. It has NO invoice number and NO
# date, which are two of the four things `validate.MANDATORY` requires.
#
# THIS IS THE FIXTURE THE WHOLE PACKAGE IS FOR. Before `status.py` this
# document and a blank page produced the same downstream silence.

MISSING_FIELDS = Fixture(
    name="no_number_and_no_date",
    text="""\
TAX INVOICE

Supplier: HALDIA PACKAGING SUPPLIES
GSTIN: 19AADFH6650N1ZR

Bill To: MITRA TRADING COMPANY
GSTIN: 19AAECM3318Q1ZD

Place of Supply: West Bengal

Description        HSN     Qty   Rate     Taxable
Corrugated boxes   4819    20    95.00    1900.00
Stretch film       3920    6     310.00   1860.00

Taxable Value: 3760.00
CGST 9%: 338.40
SGST 9%: 338.40
Total: 4436.80
""",
    expected={
        "supplier_gstin": "19AADFH6650N1ZR",
        "invoice_number": None,
        "invoice_date": None,
        "taxable_paise": 376000,
        "grand_total_paise": 443680,
        "missing": ("the bill's own number", "the date on the bill"),
    },
)


#: The six the specification asked for, plus the delivery note that separates
#: `NON_INVOICE` from `UNKNOWN_DOCUMENT`.
ALL: tuple[Fixture, ...] = (
    INTRA_STATE,
    INTER_STATE,
    WITH_DISCOUNT,
    NOT_AN_INVOICE,
    A_DELIVERY_NOTE,
    BARELY_READABLE,
    MISSING_FIELDS,
)


def text_reading(fixture: Fixture, *, confidence: float = 1.0) -> Reading:
    """The fixture as a text-layer reading - characters, one stated score."""
    return Reading.from_text(fixture.text, source=TEXT_LAYER, confidence=confidence)


def word_reading(fixture: Fixture, *, confidence: int) -> Reading:
    """The fixture as a reading rebuilt from word scores, all at `confidence`.

    ONE SCORE FOR EVERY WORD, which no real engine ever produces. It is what
    lets a test assert an EXACT field confidence: `min(word)/100` over a set of
    identical numbers is that number, so a test can pin `0.62` rather than
    asserting something vague about a range.

    THE COLUMN GAPS ARE LOST, and that is not a defect of this helper - it is
    what happens to any line rebuilt from a word list, including the real one in
    `extract/pagereader.py`. A test that used this and expected the text-layer
    answer would be testing a tier that does not exist.
    """
    return Reading.from_words(
        [
            [Word(text=word, confidence=confidence) for word in line.split()]
            for line in fixture.text.splitlines()
        ],
        source=PHOTOGRAPH,
    )
