"""The text-layer reader: the rung of the ladder that needs no pixels.

WHY THIS FILE EXISTS
--------------------
A GST e-invoice, an emailed bill and a supplier PDF all carry a TEXT LAYER -
the characters the producing program wrote, still present in the file. For
those, OCR is the wrong tool. Extraction is EXACT: the bytes say `584.10` and
there is nothing to be unsure about. OCR is for photographs and scans, which
are a different rung and a different tier.

Noticing that these are a LADDER rather than two competing readers is the whole
saving, and this file is where the top rung is held to its promise:

    it was READ, not guessed        every field it answers carries
                                    `confidence.EXACT`, which is exactly 1.0
    it never guesses instead        a PDF with no text layer says so and stops.
                                    It does not fall through to a lower rung
                                    and it does not invent a number
    it never raises                 a corrupt PDF is a refusal with a sentence,
                                    never a traceback out of `pypdf`

WHY SO MANY OF THESE TESTS ARE REFUSALS
----------------------------------------
A reader is easy to make look good: read the clean cases and stay quiet about
the rest. The dangerous output is not a blank, it is a CONFIDENT WRONG NUMBER -
a total lifted off a "PREVIOUS BALANCE" line, a `06/10/2026` read as the 6th of
October when the supplier wrote the 10th of June. Both post to a real ledger at
confidence 1.0 with nothing on screen to notice. So the tests that matter here
are the ones that prove a wrong answer is refused rather than returned, and the
corpus section below measures exactly that: how many fields are RIGHT, and how
many are WRONG rather than unread.

WHAT THIS FILE DOES NOT PROVE
------------------------------
That the reader is accurate on real customer bills. The twenty PDFs measured
below are `SYNTHETIC_EVIDENCE` generated by `scripts/build_ground_truth.py`;
they are an engineering benchmark and real-bill accuracy stays `NOT_MEASURED`
(`H-02`). A number measured here must never be reported as customer accuracy.

That a field it read is CORRECT. Exactness is about the reading, not about the
document: a supplier who prints the wrong total gets it read perfectly. That is
what the conservation laws are for, and they run afterwards.

That every PDF in the world parses. `pypdf` is one parser with its own bugs.
What is proved is that its failures come back as refusals.

NO NETWORK. The PDFs are either generated in this file or read off disk.
"""

from __future__ import annotations

import datetime
import io
import json
from collections.abc import Sequence
from decimal import Decimal
from pathlib import Path
from typing import Any

import pytest
from pypdf import PdfWriter

from accountant.cage.confidence import EXACT
from accountant.cage.wall import Field, Observation
from accountant.extract.adapter import NOT_FOUND, ExtractedRecord, Extractor
from accountant.extract.textlayer import FIELDS as MODULE_FIELDS
from accountant.extract.textlayer import (
    Outcome,
    TextLayerReader,
    TextLayerReading,
    paise_or_none,
    read,
)

REPO = Path(__file__).resolve().parent.parent
DOCUMENTS = REPO / "artifacts" / "ground_truth" / "documents"
CASES = REPO / "artifacts" / "ground_truth" / "cases"

#: The five fields this tier answers, in the order the report below prints.
FIELDS: tuple[str, ...] = ("date", "party", "total_paise", "tax_paise", "line_paise")


# ---- a PDF, built here, so the bytes under test are real ---------------------


def pdf_bytes(lines: Sequence[str], *, pages: int = 1) -> bytes:
    """A real PDF 1.4 carrying `lines` as a Helvetica text layer.

    Hand-built rather than taken from a library, for the reason
    `scripts/build_ground_truth.py` gives about the corpus: the xref offsets are
    MEASURED off the bytes as they are emitted, which is the only way a
    cross-reference table is correct. A fixture file would also work, but then
    the test could not vary one line of a bill to make a point.
    """
    per_page = max(1, -(-len(lines) // pages))
    chunks = [lines[i : i + per_page] for i in range(0, len(lines), per_page)] or [[]]
    page_ids = [3 + i for i in range(len(chunks))]
    content_ids = [3 + len(chunks) + i for i in range(len(chunks))]
    font_id = 3 + 2 * len(chunks)

    kids = " ".join(f"{i} 0 R" for i in page_ids)
    objects = [
        b"<< /Type /Catalog /Pages 2 0 R >>",
        f"<< /Type /Pages /Kids [{kids}] /Count {len(chunks)} >>".encode("ascii"),
    ]
    objects += [
        (
            f"<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources "
            f"<< /Font << /F1 {font_id} 0 R >> >> /Contents {cid} 0 R >>"
        ).encode("ascii")
        for cid in content_ids
    ]
    objects += [_content_stream(chunk) for chunk in chunks]
    objects.append(
        b"<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica "
        b"/Encoding /WinAnsiEncoding >>"
    )
    return _assemble(objects)


def _content_stream(lines: Sequence[str]) -> bytes:
    drawn = "".join(f"({_pdf_escape(line)}) Tj T*\n" for line in lines)
    stream = f"BT /F1 9 Tf 40 800 Td 12 TL\n{drawn}ET\n".encode("ascii")
    length = str(len(stream)).encode("ascii")
    return b"<< /Length " + length + b" >>\nstream\n" + stream + b"endstream"


def _pdf_escape(text: str) -> str:
    out = text.replace("\\", r"\\").replace("(", r"\(").replace(")", r"\)")
    return "".join(c if ord(c) < 128 else "?" for c in out)


def _assemble(objects: Sequence[bytes]) -> bytes:
    out = bytearray(b"%PDF-1.4\n")
    offsets: list[int] = []
    for number, body in enumerate(objects, start=1):
        offsets.append(len(out))
        out += f"{number} 0 obj\n".encode("ascii") + body + b"\nendobj\n"
    xref_at = len(out)
    out += f"xref\n0 {len(objects) + 1}\n".encode("ascii") + b"0000000000 65535 f \n"
    for offset in offsets:
        out += f"{offset:010d} 00000 n \n".encode("ascii")
    out += f"trailer\n<< /Size {len(objects) + 1} /Root 1 0 R >>\n".encode("ascii")
    out += f"startxref\n{xref_at}\n%%EOF\n".encode("ascii")
    return bytes(out)


#: An ordinary Indian purchase bill, in the shape a supplier's system prints.
BILL = (
    "TAX INVOICE",
    "INVOICE NO: TL/0001",
    "DATE: 2026-04-01",
    "SUPPLIER: SHARMA TRADERS",
    "------------------------------------------------------------",
    "DESCRIPTION                                  AMOUNT",
    "PORTLAND CEMENT 53 GRADE                           1,000.00",
    "PACKAGING MATERIAL                                    46.24",
    "------------------------------------------------------------",
    "SUBTOTAL                                           1,046.24",
    "GST                                                  188.32",
    "TOTAL                                              1,234.56",
)


#: The rule a bill prints above and below its itemised table.
RULE = "------------------------------------------------------------"
DATE_LINE = "DATE: 2026-04-01"
TAX_LINE = "GST                                                  188.32"
TOTAL_LINE = "TOTAL                                              1,234.56"
ITEM_LINE = "PACKAGING MATERIAL                                    46.24"


def bill_with(*replacements: tuple[str, str]) -> TextLayerReading:
    """`BILL`, with whole lines swapped, read back through the reader."""
    lines: list[str] = list(BILL)
    for old, new in replacements:
        lines[lines.index(old)] = new
    return read(pdf_bytes(lines))


# ---- it was read, not guessed ------------------------------------------------


def test_a_bill_with_a_text_layer_is_reported_as_read() -> None:
    assert read(pdf_bytes(BILL)).outcome is Outcome.READ


def test_the_date_printed_on_the_bill_is_the_date_returned() -> None:
    assert read(pdf_bytes(BILL)).observation.date.value == datetime.date(2026, 4, 1)


def test_the_supplier_printed_on_the_bill_is_the_party_returned() -> None:
    assert read(pdf_bytes(BILL)).observation.party.value == "SHARMA TRADERS"


def test_a_grouped_rupee_total_becomes_integer_paise() -> None:
    """`1,234.56` is 123456 paise. Not 1234.56 rupees, and never a float."""
    assert read(pdf_bytes(BILL)).observation.total_paise.value == 123_456


def test_the_tax_line_is_read_separately_from_the_total() -> None:
    assert read(pdf_bytes(BILL)).observation.tax_paise.value == 18_832


def test_the_line_items_are_read_as_integer_paise_in_printed_order() -> None:
    assert read(pdf_bytes(BILL)).observation.line_paise == (100_000, 4_624)


def test_every_field_read_off_a_text_layer_carries_confidence_exactly_one() -> None:
    """EXACT, not "very high". There is no pixel here and no estimate: the file
    says `1,234.56` in characters somebody's software wrote. A score of 0.99
    would be a claim about uncertainty that does not exist."""
    fields = read(pdf_bytes(BILL)).fields
    assert [f.confidence for f in fields.values()] == [EXACT] * len(FIELDS)
    assert EXACT == 1.0
    # The list above is only as good as the names in it. Pinning the module's
    # own tuple is what stops a field being dropped from `fields` and the
    # length check quietly agreeing with the shorter list.
    assert MODULE_FIELDS == FIELDS
    assert set(fields) == set(FIELDS)


def test_the_control_a_field_this_bill_does_not_carry_scores_zero_not_one() -> None:
    """THE CONTROL on the test above. A reader that stamped `EXACT` on the
    record rather than on each field it actually read would pass that test and
    fail this one, and would then hand the decision layer a 1.0 for a field
    nobody read."""
    reading = bill_with(("DATE: 2026-04-01", "INVOICE DATED SOMETIME LAST YEAR"))
    assert reading.observation.date.value is None
    assert reading.observation.date.confidence == 0.0


def test_an_unread_field_still_says_where_it_came_from() -> None:
    reading = bill_with(("DATE: 2026-04-01", "NO DATE PRINTED HERE"))
    assert reading.observation.date.source.startswith(NOT_FOUND)


def test_every_amount_returned_is_an_int_and_never_a_float_or_a_bool() -> None:
    """Money is integer paise everywhere in this repository. `bool` is refused
    with the ints because `isinstance(True, int)` is True in Python, so a flag
    that reached an amount would balance a one-paisa entry."""
    observation = read(pdf_bytes(BILL)).observation
    amounts = [observation.total_paise.value, observation.tax_paise.value]
    amounts += list(observation.line_paise or ())
    assert all(type(a) is int for a in amounts)


# ---- money: parsed exactly, or refused ---------------------------------------


def test_a_grouped_rupee_string_becomes_paise() -> None:
    assert paise_or_none("1,234.56") == 123_456


def test_the_currency_decoration_a_supplier_prints_does_not_stop_the_parse() -> None:
    assert paise_or_none("RS. 1,234.56") == 123_456
    assert paise_or_none("1,234.56 GBP") == 123_456
    assert paise_or_none("₹ 1,234.56") == 123_456


def test_a_negative_amount_keeps_its_sign_because_a_credit_note_is_real() -> None:
    assert paise_or_none("-485.70") == -48_570


def test_sub_paise_precision_is_refused_rather_than_rounded_away() -> None:
    """`10.005` is not 1000 paise. Rounding invoice arithmetic is how a
    reconciliation breaks three months later, and `tallyio.paise_from_rupees`
    has always refused the same string - one rule, not two."""
    assert paise_or_none("10.005") is None


def test_a_word_that_decimal_would_swallow_is_not_an_amount() -> None:
    """`Decimal("NaN")` and `Decimal("Infinity")` both parse. Handing either to
    a paise conversion is an OverflowError two frames later, or worse, a number.
    Neither is an amount a supplier printed."""
    assert paise_or_none("NaN") is None
    assert paise_or_none("Infinity") is None
    assert paise_or_none("1e5") is None


def test_an_empty_string_is_not_zero() -> None:
    assert paise_or_none("") is None
    assert paise_or_none("   ") is None


# ---- dates: read when the order is determined, refused when it is a guess -----


def test_an_iso_date_is_read() -> None:
    assert bill_with(("DATE: 2026-04-01", "DATE: 2026-11-23")).observation.date.value


def test_a_long_form_date_is_read_without_the_machine_locale() -> None:
    """`%b` follows the machine's locale, so a bill that parses on one machine
    and not another is not a reading. The month names are written down here."""
    reading = bill_with(("DATE: 2026-04-01", "DATE: 28 APR 2026"))
    assert reading.observation.date.value == datetime.date(2026, 4, 28)


def test_a_day_above_twelve_settles_the_order_by_arithmetic() -> None:
    """`26/02/2026` can only be the 26th of February. Nothing is assumed about
    the supplier's locale: 26 is not a month, so the order is determined."""
    reading = bill_with(("DATE: 2026-04-01", "DATE: 26/02/2026"))
    assert reading.observation.date.value == datetime.date(2026, 2, 26)


def test_a_month_first_date_is_read_when_that_is_the_only_reading() -> None:
    reading = bill_with(("DATE: 2026-04-01", "DATE: 01/25/2026"))
    assert reading.observation.date.value == datetime.date(2026, 1, 25)


def test_a_date_that_could_be_two_different_days_is_refused_not_guessed() -> None:
    """`06/10/2026` is the 6th of October to a supplier in Delhi and the 10th of
    June to one in Dallas. A field on this rung carries confidence 1.0, and a
    locale convention is not a reading - it is a guess wearing a certainty. The
    wrong one of these files a GST return in the wrong month."""
    reading = bill_with(("DATE: 2026-04-01", "DATE: 06/10/2026"))
    assert reading.observation.date.value is None
    assert "either" in reading.observation.date.source


def test_the_same_number_twice_is_the_same_day_whichever_way_it_is_read() -> None:
    """`05/05/2026` needs no convention: both readings are the 5th of May, so
    it is determined by arithmetic like the others and is not a guess."""
    reading = bill_with((DATE_LINE, "DATE: 05/05/2026"))
    assert reading.observation.date.value == datetime.date(2026, 5, 5)


def test_an_impossible_date_is_refused() -> None:
    """The 34th of a month is a misread 04th or 14th, not a date."""
    reading = bill_with(("DATE: 2026-04-01", "DATE: 2026-02-34"))
    assert reading.observation.date.value is None


def test_a_second_date_that_disagrees_leaves_the_date_unread() -> None:
    lines = [*BILL, "DATE: 2026-05-09"]
    assert read(pdf_bytes(lines)).observation.date.value is None


def test_a_two_page_bill_with_a_continuation_sheet_reads_as_one_document() -> None:
    """A real bill runs over. The second sheet repeats the header and the total,
    which is REPETITION and not disagreement - and it is the shape two of the
    twenty corpus PDFs actually have."""
    lines = [
        *BILL,
        "PAGE 1 OF 2",
        "CONTINUATION SHEET",
        "SUPPLIER: SHARMA TRADERS",
        TOTAL_LINE,
        "PAGE 2 OF 2",
    ]
    reading = read(pdf_bytes(lines, pages=2))
    assert reading.pages == 2
    assert reading.observation.total_paise.value == 123_456
    assert reading.observation.party.value == "SHARMA TRADERS"


def test_the_control_a_second_date_that_agrees_is_still_read() -> None:
    """THE CONTROL on the test above. A continuation sheet repeats the header,
    and a reader that refused every repeated field would refuse every
    multi-page bill. What is refused is DISAGREEMENT, not repetition."""
    lines = [*BILL, "DATE: 2026-04-01"]
    assert read(pdf_bytes(lines)).observation.date.value == datetime.date(2026, 4, 1)


# ---- totals and tax: the lines that look alike -------------------------------


def test_a_subtotal_line_is_never_read_as_the_total() -> None:
    """`SUBTOTAL` contains the word `TOTAL`. A substring match here reads
    1,046.24 as the amount payable and the bill is short by the whole tax."""
    assert read(pdf_bytes(BILL)).observation.total_paise.value == 123_456


def test_the_other_names_a_supplier_gives_the_total_are_read() -> None:
    for label in ("GRAND TOTAL", "TOTAL DUE", "AMOUNT PAYABLE"):
        reading = bill_with((TOTAL_LINE, f"{label}                    1,234.56"))
        assert reading.observation.total_paise.value == 123_456, label


def test_two_totals_that_disagree_leave_the_total_unread() -> None:
    """One of them is wrong and nothing here can say which. Picking the first
    is a coin toss that posts money."""
    lines = [*BILL, "TOTAL                                              9,999.00"]
    assert read(pdf_bytes(lines)).observation.total_paise.value is None


def test_a_split_cgst_and_sgst_are_added_into_the_one_tax_figure() -> None:
    """An intra-state bill prints the tax as two halves. Reading only one posts
    half the input credit, which is real money lost with nothing to notice.
    Adding two figures that were both read exactly is still a reading."""
    lines = [*BILL]
    lines[lines.index(TAX_LINE)] = "CGST                                    94.16"
    lines.insert(-1, "SGST                                                  94.16")
    assert read(pdf_bytes(lines)).observation.tax_paise.value == 18_832


def test_a_bill_showing_both_a_combined_and_a_split_tax_is_refused() -> None:
    """Adding all three double-counts; taking the combined one alone assumes the
    split is a breakdown of it. Neither is a reading, so nothing is returned."""
    lines = [*BILL, "CGST                                                  94.16"]
    assert read(pdf_bytes(lines)).observation.tax_paise.value is None


def test_a_split_tax_reprinted_on_a_continuation_sheet_is_not_counted_twice() -> None:
    """A two-page bill reprints its footer, and the total path already treats a
    repeat as one fact. The SPLIT tax path added every printing instead, so this
    bill came back at 376.64 - double, at confidence 1.0, from a document that
    said 188.32 twice. Repetition is ordinary; only disagreement is refused."""
    footer = ["CGST   94.16", "SGST   94.16", TOTAL_LINE]
    lines = [
        *BILL[:-2],
        *footer,
        "CONTINUATION SHEET",
        "SUPPLIER: SHARMA TRADERS",
        *footer,
    ]
    assert read(pdf_bytes(lines, pages=2)).observation.tax_paise.value == 18_832


def test_the_control_two_disagreeing_cgst_lines_leave_the_tax_unread() -> None:
    """THE CONTROL on the test above. Collapsing repeats with `set` or `max`
    would pass it and silently pick a figure here, where the two printings
    contradict each other and nothing in the bytes says which is the bill's."""
    lines = [*BILL[:-2], "CGST   94.16", "SGST   94.16", TOTAL_LINE, "CGST   99.99"]
    assert read(pdf_bytes(lines)).observation.tax_paise.value is None


def test_the_tax_invoice_heading_is_not_read_as_a_tax_amount() -> None:
    """`TAX INVOICE` starts with a tax label. A reader that took the last number
    on any line beginning `TAX` would read the invoice number as the GST."""
    lines = [*BILL]
    lines[0] = "TAX INVOICE 2026"
    assert read(pdf_bytes(lines)).observation.tax_paise.value == 18_832


def test_a_decoy_balance_line_is_not_read_as_the_total() -> None:
    """Real bills carry `PREVIOUS BALANCE` and `CREDIT NOTE APPLIED` lines. They
    are amounts, they are not this bill's amounts."""
    lines = [*BILL, "PREVIOUS BALANCE: 9,999.00", "CREDIT NOTE EARLIER: 250.00"]
    assert read(pdf_bytes(lines)).observation.total_paise.value == 123_456


def test_a_total_that_will_not_parse_is_left_unread_rather_than_coerced() -> None:
    assert bill_with((TOTAL_LINE, "TOTAL   NaN")).observation.total_paise.value is None


def test_a_total_carrying_sub_paise_precision_is_left_unread() -> None:
    reading = bill_with((TOTAL_LINE, "TOTAL                        1,234.565"))
    assert reading.observation.total_paise.value is None


# ---- line items: none read is not the same as none printed -------------------


def test_a_bill_with_no_itemised_block_leaves_the_lines_unread_not_empty() -> None:
    """`None` is "we did not read the lines"; `()` is "there are none". The
    difference is the difference between INDETERMINATE and FAIL in
    `conservation.lines_sum_to_total`, and an un-itemised bill is not a bill
    whose arithmetic is wrong - it is one we could not check."""
    lines = (
        "TAX INVOICE",
        DATE_LINE,
        "SUPPLIER: SHARMA TRADERS",
        "SUPPLY AS PER AGREEMENT. NO ITEMISED BREAKDOWN.",
        TAX_LINE,
        TOTAL_LINE,
    )
    reading = read(pdf_bytes(lines))
    assert reading.observation.line_paise is None
    assert reading.observation.total_paise.value == 123_456


def test_a_negative_line_keeps_its_sign_because_a_discount_is_a_line() -> None:
    lines = [*BILL]
    lines.insert(8, "VOLUME DISCOUNT                                     -485.70")
    assert read(pdf_bytes(lines)).observation.line_paise == (100_000, 4_624, -48_570)


def test_one_unreadable_line_makes_the_whole_block_unread() -> None:
    """Silently skipping the line it could not read would produce a tuple that
    sums to less than the total, and `lines_sum_to_total` would report the bill
    as wrong when the reader is the thing that failed."""
    reading = bill_with((ITEM_LINE, "PACKAGING MATERIAL              46.245"))
    assert reading.observation.line_paise is None


def test_a_pipe_ruled_table_is_read_the_same_as_a_plain_one() -> None:
    lines = [*BILL]
    lines[6] = "| PORTLAND CEMENT 53 GRADE      |          RS. 1,000.00|"
    lines[7] = "| PACKAGING MATERIAL            |             RS. 46.24|"
    assert read(pdf_bytes(lines)).observation.line_paise == (100_000, 4_624)


def test_a_footer_is_not_read_as_a_line_item_when_no_rule_closes_the_table() -> None:
    """Not every bill draws a rule under its items; some just start the footer.

    `SUBTOTAL   1,000.00` is shaped exactly like a line item, so a reader that
    only closes the block on a drawn rule reads the subtotal, the tax and the
    total as three more lines. Those sum to more than twice the bill, and
    `lines_sum_to_total` then reports the SUPPLIER as wrong.

    This is also what makes skipping a blank page-join line safe: without a
    footer guard, a table with no closing rule runs to the end of the document.
    """
    lines = [
        "SUPPLIER: SHARMA TRADERS",
        "DESCRIPTION                                  AMOUNT",
        "PORTLAND CEMENT 53 GRADE                           1,000.00",
        "SUBTOTAL                                           1,000.00",
        TAX_LINE,
        TOTAL_LINE,
    ]
    assert read(pdf_bytes(lines)).observation.line_paise == (100_000,)


def test_the_control_an_item_named_after_a_footer_label_is_still_an_item() -> None:
    """THE CONTROL on the test above. Closing the block on any line STARTING
    with a footer word would pass it and then drop every line after an item
    called `TAX CONSULTANCY` - which makes the lines stop adding up to the
    total, and gets the bill blamed for the reader. The footer test is "a label
    and then nothing but an amount", not a prefix."""
    lines = [*BILL]
    lines[6] = "TAX CONSULTANCY SERVICES                           1,000.00"
    assert read(pdf_bytes(lines)).observation.line_paise == (100_000, 4_624)


def test_the_descriptions_beside_the_line_amounts_are_kept() -> None:
    assert [line.description for line in read(pdf_bytes(BILL)).lines] == [
        "PORTLAND CEMENT 53 GRADE",
        "PACKAGING MATERIAL",
    ]


def test_a_second_itemised_block_is_refused_rather_than_added_to_the_first() -> None:
    """A continuation sheet that reprints the table produced `(100000, 100000)`
    from a bill with one line. Those do not add up to the total, so
    `lines_sum_to_total` reports the BILL as wrong when the READER is what
    failed - the exact harm `_read_lines` is written to avoid.

    Refused rather than de-duplicated: a second block is either the same table
    reprinted or genuinely more items, and the document does not say which. A
    guess here is a wrong tuple at confidence 1.0."""
    reprinted = [*BILL, "CONTINUATION SHEET", *BILL[5:9]]
    assert read(pdf_bytes(reprinted, pages=2)).observation.line_paise is None


def test_the_control_one_itemised_block_split_by_a_page_break_still_reads() -> None:
    """THE CONTROL on the test above. A bill whose table runs over a page break
    carries ONE header - `BILL` splits with the header ending page 1 and both
    items on page 2 - so a reader that refused every multi-page bill's lines
    would fail this. What is refused is a SECOND header, not a second page."""
    assert read(pdf_bytes(BILL, pages=2)).observation.line_paise == (100_000, 4_624)


# ---- no text layer: the other rung's job, said out loud ----------------------


def test_a_pdf_with_no_text_layer_says_so_rather_than_guessing() -> None:
    """A scan or a photograph. Every field comes back unread, with a sentence,
    and nothing on this rung tries to read a pixel."""
    reading = read(_blank_pdf())
    assert reading.outcome is Outcome.NO_TEXT_LAYER
    assert all(field.value is None for field in reading.fields.values())


def test_the_control_a_pdf_with_no_text_layer_is_not_called_corrupt() -> None:
    """THE CONTROL. The file is perfectly valid - it simply carries no
    characters. Reporting it as unreadable would send somebody hunting a broken
    file when what they have is a scan, which is the OCR tier's input."""
    assert read(_blank_pdf()).outcome is not Outcome.UNREADABLE


def test_the_refusal_for_a_scan_names_the_tier_that_does_read_pixels() -> None:
    said = read(_blank_pdf()).said
    assert "text layer" in said and ("scan" in said or "photograph" in said)


def _blank_pdf() -> bytes:
    writer = PdfWriter()
    _ = writer.add_blank_page(width=200, height=200)
    buffer = io.BytesIO()
    writer.write(buffer)
    return buffer.getvalue()


# ---- fails closed: a parser failure is a refusal, never a traceback ----------


def test_bytes_that_are_not_a_pdf_at_all_are_refused() -> None:
    reading = read(b"paid Sharma Traders 4200 for cement")
    assert reading.outcome is Outcome.UNREADABLE
    assert all(field.value is None for field in reading.fields.values())


def test_the_refusal_for_non_pdf_bytes_names_the_header_they_are_missing() -> None:
    """Asserting only the outcome above proves nothing about the header check:
    `pypdf` also refuses these bytes, and its refusal reads "PdfStreamError".
    What the check buys is a sentence a person can act on - and the bytes never
    reaching an untrusted parser at all - so the sentence is what is pinned."""
    assert "%PDF-" in read(b"paid Sharma Traders 4200 for cement").said


def test_empty_bytes_are_refused_and_are_not_an_empty_bill() -> None:
    assert read(b"").outcome is Outcome.UNREADABLE


def test_a_truncated_pdf_is_refused_without_an_exception_escaping() -> None:
    """Half a file is what an interrupted upload leaves behind. `pypdf` raises
    on it, and an exception here is an HTTP 503 saying the application broke -
    for a person whose only problem is a dropped connection."""
    whole = pdf_bytes(BILL)
    reading = read(whole[: len(whole) // 2])
    assert reading.outcome is Outcome.UNREADABLE
    assert reading.said.strip()


def test_a_pdf_declaring_no_pages_is_refused_rather_than_called_a_scan() -> None:
    """Zero pages is not a document with nothing printed on it. Calling it a
    scan would send a structurally broken file to the OCR tier, which would
    read noise out of it rather than refusing it."""
    headless = pdf_bytes(BILL).replace(b"/Kids [3 0 R]", b"/Kids [99 0 R]")
    assert read(headless).outcome is Outcome.UNREADABLE


def test_an_encrypted_pdf_is_refused_rather_than_half_read() -> None:
    """We hold no password and must not guess one. The refusal says the file is
    locked, which is a sentence the person can act on."""
    reading = read(_encrypted_pdf())
    assert reading.outcome is Outcome.UNREADABLE
    assert "encrypt" in reading.said or "password" in reading.said


def _encrypted_pdf() -> bytes:
    writer = PdfWriter()
    _ = writer.add_blank_page(width=200, height=200)
    writer.encrypt("not-a-real-password")
    buffer = io.BytesIO()
    writer.write(buffer)
    return buffer.getvalue()


def test_every_refusal_carries_a_sentence_a_person_can_read() -> None:
    for data in (b"", b"not a pdf", _blank_pdf(), _encrypted_pdf()):
        assert read(data).said.strip(), data[:8]


def test_reading_the_same_bytes_twice_gives_the_identical_answer() -> None:
    """Determinism. Text extraction has no excuse to vary, and a test that says
    so is what stops somebody adding a clock, a cache or a model later."""
    data = pdf_bytes(BILL)
    assert read(data) == read(data)


def test_a_reading_cannot_be_edited_after_it_is_made() -> None:
    reading = read(pdf_bytes(BILL))
    with pytest.raises(AttributeError):
        reading.outcome = Outcome.UNREADABLE  # type: ignore[misc]


# ---- security: pypdf parses untrusted bytes in this process ------------------


def test_an_embedded_file_reference_is_not_followed(tmp_path: Path) -> None:
    """A PDF may name another file and ask that it be opened. Following that is
    how a document reader becomes a file-disclosure bug.

    The named file is REAL and carries a marker this test wrote, so the check
    is falsifiable: a reader that followed the reference would put the marker
    in the text it returns, and this assertion would fail. Pointing at a path
    that does not exist would pass no matter what the reader did."""
    secret = tmp_path / "secret.txt"
    _ = secret.write_text("MARKER-8f31-DO-NOT-READ-ME", encoding="utf-8")
    poisoned = pdf_bytes(BILL).replace(
        b"/Type /Catalog",
        b"/Type /Catalog /OpenAction << /S /Launch /F ("
        + str(secret).encode("ascii")
        + b") >>",
    )
    reading = read(poisoned)
    assert "MARKER-8f31" not in reading.text
    assert reading.observation.total_paise.value == 123_456


def test_a_page_tree_that_points_at_itself_does_not_hang_or_crash() -> None:
    """A self-referential /Kids is a two-line edit to a file and an infinite
    loop in a naive reader."""
    looping = pdf_bytes(BILL).replace(b"/Kids [3 0 R]", b"/Kids [2 0 R]")
    assert read(looping).said.strip()


# ---- the seam: it plugs in where the other backends already do ---------------


def test_the_reader_satisfies_the_extractor_protocol_unchanged() -> None:
    """The seam is `adapter.Extractor`, and this rung joins it rather than
    redesigning it. A new Protocol would mean every caller learns a second way
    to ask the same question."""
    assert isinstance(TextLayerReader(), Extractor)


def test_the_extractor_answers_with_a_record_every_field_of_which_is_sourced() -> None:
    record = TextLayerReader().extract(pdf_bytes(BILL), "application/pdf")
    assert isinstance(record, ExtractedRecord)
    assert record.complete


def test_the_extractor_refuses_a_media_type_that_is_not_a_pdf() -> None:
    """Handed a JPEG, this backend must say so rather than run a money regex
    over the container - which is the exact defect `TypedTextExtractor` was
    fixed for, and it returned invented totals for months."""
    record = TextLayerReader().extract(pdf_bytes(BILL), "image/jpeg")
    assert record.total_paise is None
    assert record.per_field_source["total_paise"].startswith(NOT_FOUND)


def test_the_charset_parameter_on_a_media_type_does_not_cause_a_refusal() -> None:
    record = TextLayerReader().extract(pdf_bytes(BILL), "application/pdf; qs=0.001")
    assert record.total_paise == 123_456


def test_the_record_names_this_backend_so_a_log_row_says_what_read_it() -> None:
    record = TextLayerReader().extract(pdf_bytes(BILL), "application/pdf")
    assert record.backend == TextLayerReader.name


# ---- the corpus: twenty real PDFs, measured -----------------------------------


def corpus_cases() -> list[dict[str, Any]]:
    """Every PDF case in `artifacts/ground_truth/`, newest build on disk."""
    loaded: list[dict[str, Any]] = []
    for path in sorted(CASES.glob("*.json")):
        case: dict[str, Any] = json.loads(path.read_text(encoding="utf-8"))
        if str(case["input_type"]) == "PDF":
            loaded.append(case)
    return loaded


def expected_answer(case: dict[str, Any]) -> dict[str, object]:
    """The truth the document was RENDERED FROM, converted here.

    Converted with `Decimal` in this file rather than through the reader's own
    `paise_or_none`. A comparison that used the reader to build both sides
    would agree with itself no matter how wrong it was.
    """
    expected: dict[str, Any] = case["expected"]
    items: list[dict[str, Any]] = expected["line_items"]
    return {
        "date": datetime.date.fromisoformat(str(expected["date"])),
        "party": str(expected["party"]),
        "total_paise": int(Decimal(str(expected["total_amount"])) * 100),
        "tax_paise": int(Decimal(str(expected["tax_amount"])) * 100),
        "line_paise": tuple(int(Decimal(str(i["amount"])) * 100) for i in items),
    }


def read_answer(observation: Observation) -> dict[str, object]:
    return {
        "date": observation.date.value,
        "party": observation.party.value,
        "total_paise": observation.total_paise.value,
        "tax_paise": observation.tax_paise.value,
        "line_paise": observation.line_paise,
    }


def score_corpus() -> tuple[dict[str, int], dict[str, int]]:
    """Per field: how many were EXACTLY right, and how many were WRONG.

    Wrong is the number that matters. A field left unread costs a question; a
    field read wrongly at confidence 1.0 posts a number nobody checked.
    """
    right: dict[str, int] = dict.fromkeys(FIELDS, 0)
    wrong: dict[str, int] = dict.fromkeys(FIELDS, 0)
    for case in corpus_cases():
        data = (DOCUMENTS / str(case["document"])).read_bytes()
        got = read_answer(read(data).observation)
        want = expected_answer(case)
        for name in FIELDS:
            if got[name] == want[name]:
                right[name] += 1
            elif got[name] is not None:
                wrong[name] += 1
    return right, wrong


def test_every_pdf_in_the_corpus_is_reported_as_carrying_a_text_layer() -> None:
    outcomes = {
        str(case["case_id"]): read((DOCUMENTS / str(case["document"])).read_bytes())
        for case in corpus_cases()
    }
    assert len(outcomes) == 20
    assert all(r.outcome is Outcome.READ for r in outcomes.values()), outcomes


def test_no_field_read_from_the_twenty_corpus_pdfs_is_wrong() -> None:
    """The claim that matters, and the one this tier is built to make. A field
    is either exactly the value the document was generated from, or it is
    unread. There is no third case, because the third case is a wrong number
    carrying confidence 1.0."""
    _, wrong = score_corpus()
    assert sum(wrong.values()) == 0, wrong


def test_the_measured_per_field_exact_match_on_the_twenty_corpus_pdfs() -> None:
    """MEASURED on 2026-08-13, not a target. `>=` rather than `==` so that a
    later improvement is not a failing test and a regression still is."""
    right, _ = score_corpus()
    assert right["party"] >= 20, right
    assert right["total_paise"] >= 20, right
    assert right["tax_paise"] >= 20, right
    assert right["line_paise"] >= 18, right
    assert right["date"] >= 14, right


def test_the_control_the_corpus_comparison_would_notice_a_wrong_answer() -> None:
    """THE CONTROL on the two tests above. A comparison that compared nothing
    would report zero wrong and full marks, and the two are indistinguishable
    without a case that is MEANT to mismatch and does."""
    case = corpus_cases()[0]
    want = expected_answer(case)
    stated = want["total_paise"]
    assert isinstance(stated, int)
    reading = read((DOCUMENTS / str(case["document"])).read_bytes())
    got = read_answer(reading.observation)
    assert got["total_paise"] == stated
    assert got["total_paise"] != stated + 1


def test_the_dates_the_corpus_refuses_are_refused_for_a_stated_reason() -> None:
    """The six unread dates are not a silent gap. Each one is a `DD/MM` or
    `MM/DD` that two suppliers would write for two different days, and the
    field says so where a person can read it."""
    refused = [
        read((DOCUMENTS / str(case["document"])).read_bytes()).observation.date
        for case in corpus_cases()
    ]
    unread = [field for field in refused if field.value is None]
    assert len(unread) == 6
    assert all("either" in field.source for field in unread), unread


def test_a_field_object_from_this_reader_obeys_the_wall_invariants() -> None:
    """`Field` refuses a value of None with a confidence above zero. If this
    reader ever built one, construction would raise rather than return."""
    with pytest.raises(ValueError, match=r"confidence 0\.0"):
        _ = Field(value=None, confidence=EXACT, source="pdf_text_layer")


# =============================================================================
# REVIEW NOTES
# =============================================================================
#
# Read back cold, and by running mutants against it rather than by rereading it,
# because a test file always looks convincing to the person who wrote it. Sixteen
# deliberate breakages of `textlayer.py` were run and all sixteen now die; three
# of them died only after the defect below was found and fixed. What follows is
# what the surviving mutants and a cold read turned up.
#
# 0. FIXED - TWO REAL DEFECTS, BOTH WRONG NUMBERS AT CONFIDENCE 1.0. A cold read
#    of the corpus's own two-page shape found that a continuation sheet broke
#    the reader in two separate ways, and both produced a WRONG value rather
#    than a blank, which is the one output this whole tier exists to avoid:
#
#        the split tax was summed over EVERY printing, so a bill whose footer
#        repeats CGST 94.16 / SGST 94.16 on its second sheet came back at
#        376.64 - double the tax, from a document that never contradicted
#        itself. `_split_tax` now agrees each label with its own repeats first
#        and adds one figure per label.
#
#        the itemised table was CONCATENATED across headers, so a two-line bill
#        whose table is reprinted answered `(100000, 4624, 100000, 4624)`.
#        Those do not sum to the total, so `lines_sum_to_total` would have
#        reported the BILL as wrong when the READER was what failed. A second
#        header is now refused.
#
#    And the fix for the second one exposed a third: the blank line that a page
#    join puts between two pages was being treated as the rule that closes the
#    table, so a table split across a page break read as no items at all.
#
#    All three are the same lesson. The corpus has two multi-page cases and both
#    happened to be shaped so that the bugs cancelled out; a test built on the
#    SHAPE rather than on the sample is what found them.
#
# 1. FIXED. `test_bytes_that_are_not_a_pdf_at_all_are_refused` passed for the
#    wrong reason. Deleting the `%PDF-` header check from the module left all
#    63 tests green, because `pypdf` refuses the same bytes on its own - so the
#    test proved nothing about the check. What the check actually buys is the
#    SENTENCE ("these bytes are not a PDF") instead of "PdfStreamError", and
#    the untrusted bytes never reaching the parser.
#    `test_the_refusal_for_non_pdf_bytes_names_the_header_they_are_missing`
#    now pins that, and the mutant dies.
#
# 2. FIXED. `test_an_embedded_file_reference_is_not_followed` asserted that
#    `"root:"` was absent from the extracted text after pointing an
#    `/OpenAction /Launch` at `/etc/passwd`. That assertion could not fail: the
#    reader would have had to both follow the reference AND inline the result
#    into `text`. It now writes a real file with a known marker and points the
#    action at THAT, so a reader which followed the reference would put the
#    marker where the assertion looks.
#
# 3. FIXED. `pdf_bytes(pages=...)` was never called with anything but the
#    default, so the helper's own page-splitting was dead code here and the
#    two-page shape was only covered through the corpus. A continuation-sheet
#    test now exercises it, and it doubles as a check that a repeated total is
#    read as repetition rather than as disagreement.
#
# 4. FIXED. The test file's `FIELDS` was a second copy of the module's. Dropping
#    a field from the module would have shortened both `fields` and the expected
#    list, and the confidence test would have agreed with the shorter one. The
#    module's tuple is now imported and pinned.
#
# 5. NOT FIXED, and stated rather than done. Four tests each read and parse all
#    twenty corpus PDFs, so the corpus is walked four times. Measured, the whole
#    file runs in about a second, so this is not the bottleneck and caching it
#    in module state would add exactly the kind of hidden shared state that
#    makes a parallel run flaky.
#
# 6. NOT FIXED, owner-blocked. There is no test that a very large or deeply
#    nested PDF is refused, because a size or page cap is a NUMBER and nobody
#    has set one. Inventing "50 MB" here would put a threshold in the product
#    that no one owns. Reported as owner work instead.
#
# 9. FIXED, and found by a SURVIVING MUTANT rather than by reading. Deleting
#    `_is_footer_row` from the condition that closes the itemised block left
#    every test green - so the guard that makes skipping a blank page-join line
#    safe was carrying no test at all. What it buys: a bill that starts its
#    footer without drawing a rule under the items had `SUBTOTAL`, `GST` and
#    `TOTAL` read as three more line items, and those sum to over twice the
#    bill, so the SUPPLIER gets blamed for the reader.
#
#    Its paired control matters as much. Testing the footer as a PREFIX would
#    also kill the first mutant, and would then drop every line after an item
#    called `TAX CONSULTANCY SERVICES`. Both mutants are now run and both die.
#
# 8. NOT FIXED, and it is an OWNER QUESTION rather than a bug. Measured: take a
#    good PDF, corrupt only its `startxref` pointer, and `pypdf` rebuilds the
#    cross-reference table by scanning the file for `N 0 obj` and reads the bill
#    perfectly - 123456 paise, `Outcome.READ`, confidence 1.0. That recovery is
#    a RECONSTRUCTION, and this rung's entire claim is that nothing it returns
#    was guessed.
#
#    It is not cosmetic. In an incrementally updated PDF the xref chain is the
#    only thing saying which version of an object is current, so a rebuild can
#    hand back a superseded total in good faith - and "append a new total, break
#    the xref" is what a tampered invoice looks like.
#
#    Refusing it is about twenty lines (`rfind(b"startxref")`, parse the offset,
#    check `xref` or `N 0 obj` is actually there - verified working against all
#    twenty corpus PDFs, the blank PDF and the encrypted one). It is NOT done
#    here because it would also refuse real supplier PDFs that `pypdf` recovers
#    correctly today, and choosing between "refuse a recoverable real bill" and
#    "accept a reconstruction" is a product decision with a cost on both sides.
#    Nobody has made it, so it is reported rather than assumed.
#
# 7. NOT FIXED, deliberately. `conservation.py` pins its own import list so a
#    dependency cannot arrive behind an import nobody rereads. The same test is
#    not written here because this module imports `pypdf` on purpose, and an
#    allow-list over a third-party package's own transitive imports would fail
#    on a routine upgrade rather than on a real change.
